### ISSUE TITLE
Adjust text size

### ISSUE THREAD

**Issue by MrTomRod** [1337kid/NoiceGRUB#5]
Hey!

I really like your theme, but my screen has a resolution of 3000x2000, and I would like to increase the text size. I didn't manage.

Can you tell me how this can be done?

Best, MrTomRod

**Comment by MrTomRod** [comment]
Thanks for your help. This is what I tried:

```bash
grub2-mkfont -v --output=/boot/grub2/themes/noicegrub/DejaVuSansMono.pf2 --size=48 /usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf
grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg  # update-grub equivalent on Fedora 39
````

It didn't work, unfortunately. Is it enough if the font is in this directory?

![20231125_165658](https://github.com/1337kid/NoiceGRUB/assets/40867365/b24c6514-3456-4b7f-83d6-ba908b674be4)

**Comment by 1337kid** [comment]
Oh, I didn't know that you were using Fedora. In the case of Ubuntu, the above steps will mostly work.
For Fedora, I think its necessary to specify the location of pf2 file in the GRUB config.
Add the below line to `/etc/default/grub`
```
GRUB_FONT=/boot/grub2/themes/noicegrub/DejaVuSansMono.pf2
```
then update GRUB
```bash
grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
```

I hope this helps

**Comment by 1337kid** [comment]
Hi,
There will be an issue after increasing the font size. On pressing the arrow keys, selected OS will be highlighted. By default the height is 30px. I'm working on a fix so that the user can set the font size and an appropriate height will be given for the selection box

**Comment by 1337kid** [comment]
Hi,
This issue was implemented as a new feature. Also, the user can provide their own fonts.
Update NoiceGRUB and enjoy :)

1337kid

**Comment by MrTomRod** [comment]
Thanks a lot, this is great!
